### PR TITLE
Add TMPDIR environment variables to handle non-default temp directories

### PR DESCRIPTION
**Pull request by marcelzwiers**
See Github issue #11

### CODE REVIEW

**Comment by stebo85** [comment]
thank you for sending that pull request. I am hoping to be able to test this next week. Did you test your changes on your system and did it work? I think it also needs mount points in addition for this to work?

**Comment by marcelzwiers** [comment]
Yes, you are right. I copied over what I had on our HPC, but indeed for us the non-default tmpdir is automatically mounted on all apptainers. So perhaps it is better to script this and check if any of the TMPDIR variables (as used in this PR) are non-empty and then bindmount them as `/tmp`?

**Comment by marcelzwiers** [comment]
So something like:

```bash
CUSTOMTMPDIR="/tmp"
for CUSTOMDIR in $TMP $TMPDIR $TEMP $TEMPDIR; do
   CUSTOMTMPDIR=$CUSTOMDIR
done

apptainer run --cleanenv --no-mount tmp --bind ${CUSTOMTMPDIR}:/tmp etc
```

**Comment by stebo85** [comment]
cool! Does this work on your system now? Then I test on the HPCs I have access to and we can make it available for all

**Comment by marcelzwiers** [comment]
If I manually edit our singularity run-scripts likewise then it works for us :-)

**Comment by stebo85** [comment]
thank you for confirming :)

**Comment by marcelzwiers** [comment]
I didn't look into setting this bind option centrally, perhaps that is also possible as an alternative

**Comment by marcelzwiers** [comment]
https://apptainer.org/docs/user/main/bind_paths_and_mounts.html#system-defined-bind-paths
https://apptainer.org/docs/user/main/cli/apptainer_config_global.html#apptainer-config-global

**Comment by stebo85** [comment]
yes, that would also be possible

**Comment by marcelzwiers** [comment]
Indeed, I now see that there exists a variable for this, i.e. `APPTAINER_WORKDIR` (see [here](https://apptainer.org/docs/user/main/appendix.html#w)). But that also does something with the HOME directory?

**Comment by marcelzwiers** [comment]
I just tested the new run_fetch code and it works nicely :-)

**Pull request merged**
